### ISSUE TITLE
Getting open source in the frontend side

### ISSUE THREAD

**Issue by JoelAngels** [EddieJaoudeCommunity/support#77] opened 2020-08-19 14:36 UTC
Eddie, can you help me find a front-end open source project, and btw I joined your discord.

**Comment by eddiejaoude** [comment] 2020-08-19 21:08
I will close this because it is a duplicate of https://github.com/EddieJaoudeCommunity/support/issues/76

**Closed by eddiejaoude** 2020-08-19 21:08 UTC
Labels: question
